### ISSUE TITLE
issue order id

### ISSUE THREAD

**Issue by KristofStroobants** [Civil-Cucumber/TradingViewDataAssembler_Public#1]
`KeyNotFoundException: The given key 'Order id' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <697c5b3fd45741b99b7cab46a4b7b6ac>:0 
  at TradingViewDataAssembler.GetHistoryEntries (System.Globalization.CultureInfo floatCulture, System.Collections.Generic.List`1[T] history) [0x0017c] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\TradingViewDataAssembler.cs:314 
  at TradingViewDataAssembler.AssembleData (FileManager+TradingViewData tradingViewData) [0x00012] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\TradingViewDataAssembler.cs:92 
  at Initializer.ConvertData () [0x00015] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\Initializer.cs:20 
  at Initializer.Start () [0x0000d] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\Initializer.cs:12 

(Filename: C:/Users/marku/Documents/GitHub/TradingViewDataAssembler_Public/Assets/Scripts/TradingViewDataAssembler.cs Line: 314)`

this is what i get when trying to use this. might have a hard coded reference?

**Comment by Qxlb3r** [comment]
Hmm this means that your History.csv doesn't have a column "order id".

There could be 2 possible reasons causing that problem:

1. Your TradingView's language is not set to English (so the column "Order Id" might be translated into your native language, which is not supported). 

**To fix it:** set TradingView's language to English.

2. The column "order id" is deactivated in the History tab. 

**To fix it:** In TradingView Papertrading go to the "History" tab, then click on the 3 dots in the upper right corner, and make sure ALL categories have a checkmark.

Can you check both, then export files and run TradingViewDataAssembler again, and then let me know if that fixed it?

**Comment by KristofStroobants** [comment]
`UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Log (object)
TradingViewDataAssembler:GetHistoryEntries (System.Globalization.CultureInfo,System.Collections.Generic.List`1<System.Collections.Generic.Dictionary`2<string, string>>) (at C:/Users/marku/Documents/GitHub/TradingViewDataAssembler_Public/Assets/Scripts/TradingViewDataAssembler.cs:338)
TradingViewDataAssembler:AssembleData (FileManager/TradingViewData) (at C:/Users/marku/Documents/GitHub/TradingViewDataAssembler_Public/Assets/Scripts/TradingViewDataAssembler.cs:92)
Initializer:ConvertData () (at C:/Users/marku/Documents/GitHub/TradingViewDataAssembler_Public/Assets/Scripts/Initializer.cs:20)
Initializer:Start () (at C:/Users/marku/Documents/GitHub/TradingViewDataAssembler_Public/Assets/Scripts/Initializer.cs:12)

(Filename: C:/Users/marku/Documents/GitHub/TradingViewDataAssembler_Public/Assets/Scripts/TradingViewDataAssembler.cs Line: 338)

FormatException: Input string was not in a correct format.
  at System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) [0x0001a] in <697c5b3fd45741b99b7cab46a4b7b6ac>:0 
  at System.Number.ParseSingle (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) [0x00071] in <697c5b3fd45741b99b7cab46a4b7b6ac>:0 
  at System.Single.Parse (System.String s, System.IFormatProvider provider) [0x0001b] in <697c5b3fd45741b99b7cab46a4b7b6ac>:0 
  at TradingViewDataAssembler.GetPositionsEntries (System.Globalization.CultureInfo floatCulture, System.Collections.Generic.List`1[T] positions) [0x000b6] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\TradingViewDataAssembler.cs:380 
  at TradingViewDataAssembler.AssembleData (FileManager+TradingViewData tradingViewData) [0x00020] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\TradingViewDataAssembler.cs:93 
  at Initializer.ConvertData () [0x00015] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\Initializer.cs:20 
  at Initializer.Start () [0x0000d] in C:\Users\marku\Documents\GitHub\TradingViewDataAssembler_Public\Assets\Scripts\Initializer.cs:12 

(Filename: C:/Users/marku/Documents/GitHub/TradingViewDataAssembler_Public/Assets/Scripts/TradingViewDataAssembler.cs Line: 380)
`

not i get this.

**Comment by Qxlb3r** [comment]
Hmm i don't know what exactly the reason for that error could be.

Could you maybe send your History.csv file to me, so i can try to reproduce the error on my machine?
You can send it to me via DM on Reddit in case you don't feel comfortable sharing it here: https://www.reddit.com/u/Civil-Cucumber

**Comment by KristofStroobants** [comment]
So turns out when you download the data from the website it works. If i use the files downloaded via the tradingview app it doesnt.
one last issue is that it only sees my trades from May, the ones done in June he does not spot?

**Comment by Qxlb3r** [comment]
It should be compatible with the website and the app - maybe the app still has the "wrong" language settings / column settings?

Regarding trades: unfortunately TradingView only seems to save the last 100 orders (and the cancellation of an order seems to count as an order as well). So if you also don't see  your trades from May in the "History" tab in TradingView's PaperTrading, I'm afraid that information is gone.
If you trade very frequent, I recommend using the tool at the end of each day.

**Comment by KristofStroobants** [comment]
thanks

**Comment by KristofStroobants** [comment]
> It should be compatible with the website and the app - maybe the app still has the "wrong" language settings / column settings?
> 
> Regarding trades: unfortunately TradingView only seems to save the last 100 orders (and the cancellation of an order seems to count as an order as well). So if you also don't see your trades from May in the "History" tab in TradingView's PaperTrading, I'm afraid that information is gone. If you trade very frequent, I recommend using the tool at the end of each day.

To return to this subject. I manually deleted some lines from the history csv.
It then does see the newest trades.

PS do you have the spreadsheet shared somewhere? (the one seen on your screenshots).

**Comment by Civil-Cucumber** [comment]
Sorry I only saw it now, I was on vacation.

In general I would highly recommend to create your own sheet that suits your own needs and that you know inside out.

However, here is a template version of my sheet that you can use as a starting point if you want: https://docs.google.com/spreadsheets/d/17TMQe8XxWo4iOV1H9QgTCjtktUd6ZMpVBW1UmWal0J4/edit?usp=sharing

**In order to use it, you need to create a copy of it (File --> Create copy).**

_I'm from Germany, so the whole sheet is based on the number format there. You can change the number format in File --> Preferences though._

# How to use it:

1. After having used TradingView Data Assembler, go to the **Split Data** sheet, press the **Clear** button to clear the table, then paste the data from your clipboard into cell **A2**. This splits the data into separate columns. 
_It also converts them into German format though by replacing commas with dots, so you might need to change the formulas in column B to your local format!_

2. Copy the new data you want to add (from column C to column N) and switch to the **Trading Journal** sheet.

3. I always add new entries at the very top in this sheet. So you need to type the amount of new rows you need into cell **AD1** and press the **Add Entry** button next to it. Then select **A2** and paste the data from step 2 as **values** (Right click --> paste contents --> values only (or just press the keyboard shortcut it shows there)).

That's it.

## Adding additional trade infos:

You can immediately after you made a trade write down additional infos, like why you entered, how secure you feel and so on. Therefore just press "Add entry", write down in **V2** the stock symbol (to make sure when you later paste the actual data it's in the correct row) and then in columns **W to AC** you can add additional information.

As you can see in the template I haven't used this in my most recent trades at all, since most of the time I entered trades for the same reasons, and I got a bit lazy...

## Analysis:

I use columns AD to AI to find out mistakes I made afterwards.

Besides that, in the "Analysis" sheet you can see your win rate + P/L ratio. You can calculate it for a range of trades by definining the min + max rows in cells H1 and H2.

Hope this helps you!

**Comment by KristofStroobants** [comment]
I'm Dutch native so I understand most of your German words :)

I got down a rabbit hole yesterday after trying your XLXS sheet.
I don't know how to code C# but I do know PowerShell.
Got it to work for limit orders (not market, how do you keep track of them? there is no ID referencing them. So i guess you need to check if trade is closed or not?).

Anyway, reason i tried coding it 'quickly' myself, is cause i trade crypto. My prices are with 4 decimals, your code rounds them to 2 decimals. Which then makes it impossible to calculate P/L.

Also, are you sure your first entry data is correct? It looks like 'Closing time' and not 'Fill Price' when i compared them with mine.
